### ISSUE TITLE
EventTrigger issue.

### ISSUE THREAD

**Issue by keanuplayz** [CCDirectLink/crosscode-map-editor#103] opened 2019-09-15 09:04 UTC
When creating an EventTrigger entity, you can click the event button to add events to this entity.
![image](https://user-images.githubusercontent.com/50610755/64919217-704bbc80-d7a8-11e9-9c61-3da05c788c50.png)

Whenever you click an event from the list though,
![image](https://user-images.githubusercontent.com/50610755/64919222-7772ca80-d7a8-11e9-9f5c-890f057d5622.png)

Nothing will appear in the list.
![image](https://user-images.githubusercontent.com/50610755/64919233-88234080-d7a8-11e9-8109-60555df740b0.png)

**Comment by keanuplayz** [comment] 2019-09-15 14:07
It appears this issue fixed itself randomly. I don't know what caused it before, but it works fine now.

Closing.

**Comment by ac2pic** [comment] 2019-09-15 14:15
If it appears randomly then we need to figure out the issue.

**Comment by keanuplayz** [comment] 2019-09-15 14:40
It did appear out of nowhere.

**Comment by Vegita2** [comment] 2019-09-16 13:19
i cannot reproduce it. If it ever shows `[ null events ]`

**Comment by keanuplayz** [comment] 2019-09-16 15:43
I have no clue how I even produced it in the first place.
It was on the `default-entities` branch.
I don't know anything else then the info I've already provided.

**Comment by Vegita2** [comment] 2020-04-29 12:16
open a new issue if you can reproduce it. Closing it for now

**Closed by Vegita2** 2020-04-29 12:16 UTC
Labels: bug, more info needed
