### ISSUE TITLE
Wrong destructible bounding box

### ISSUE THREAD

**Issue by 2767mr** [CCDirectLink/crosscode-map-editor#155] opened 2020-04-10 12:28 UTC
![image](https://user-images.githubusercontent.com/2082553/78990717-7421a080-7b37-11ea-8817-d7bf782d83f0.png)

**Comment by Vegita2** [comment] 2020-04-10 18:36
I cannot reproduce it
![image](https://user-images.githubusercontent.com/9483499/79014312-ec558980-7b6a-11ea-9157-3824f2807710.png)

**Comment by 2767mr** [comment] 2020-04-10 20:28
Now i cannot reproduce it either even though I am still using same binary (Built using `npm run dist`)

**Comment by Vegita2** [comment] 2020-04-11 12:00
I'll close this issue then. Feel free to reopen or make another issue if you find out how to reproduce it

**Closed by Vegita2** 2020-04-11 12:00 UTC
Labels: bug, more info needed
